//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demExam.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставЗаказа
    {
        public int Код { get; set; }
        public int НомерЗаказа { get; set; }
        public string АртикулЗаказа { get; set; }
        public int Количество { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
