//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demExam.dbModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Remoting.Contexts;

    public partial class Заказ
    {
        public Заказ()
        {
            this.СоставЗаказа = new HashSet<СоставЗаказа>();
        }

        public int Номер_заказа { get; set; }
        public System.DateTime ДатаЗаказа { get; set; }
        public System.DateTime ДатаДоставки { get; set; }
        public int КодАдресаПункта_Выдачи { get; set; }
        public int КодАвторизированногоКлиента { get; set; }
        public int КодДляПолучения { get; set; }
        public string СтатусЗаказа { get; set; }

        public virtual АдресПунктаВыдачи АдресПунктаВыдачи { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual ICollection<СоставЗаказа> СоставЗаказа { get; set; }

        //Код для вывода несколько артикулов (через запятую) с состава заказа
        public string isArticle
        {
            get
            {
                return string.Join(", ",
                    СоставЗаказа.Where(a => a.НомерЗаказа == this.Номер_заказа).Select(a => a.АртикулЗаказа)
                );
            }
        }
    }
}
