//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demExam.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public Товар()
        {
            this.СоставЗаказа = new HashSet<СоставЗаказа>();
        }
    
        public string Артикул { get; set; }
        public string НаименованиеТовара { get; set; }
        public string ЕдиницаИзмерения { get; set; }
        public double Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string КатегорияТовара { get; set; }
        public int ДействующаяСкидка { get; set; }
        public int КоличествоНаСкладе { get; set; }
        public string ОписаниеТовара { get; set; }
        public string Фото { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual ICollection<СоставЗаказа> СоставЗаказа { get; set; }

        //------------------------------------------------------------------------------
        // <auto-generated>
        //    Этот код был создан из шаблона.
        //
        //    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
        //    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
        // </auto-generated>
        //------------------------------------------------------------------------------



            //КОД ДЛЯ ЗАГРУЗКИ ФОТОГРАФИЙ (МАКСИМАЛЬНО ПРОСТО БЕЗ ВСЯКИХ ТАМ КОНВЕРТЕРОВ И ХУЙНИ).Условие (картинки должны находится в папке Assets внутри проекта)
            public string isImageLoad
            {
                get
                {
                    if (this.Фото != null)
                        return "/Assets/" + this.Фото.ToString();
                    else
                        return "/Assets/picture.png";
                }
            }

            //ПРОВЕРКА НА ЗАЧЕРКИВАНИЕ СТРОКИ С ЦЕНОЙ, И ПОКРАСКУ В КРАСНЫЙ
            public bool checkPriceCollor
            {
                get
                {
                    if (this.ДействующаяСкидка > 0)
                        return true;
                    else
                        return false;
                }
            }

            //КОД ДЛЯ РАСЧЕТА НОВОЙ ЦЕНЫ
            public decimal newPriceAction
            {
                get
                {
                    return Convert.ToDecimal(this.Цена) - (Convert.ToDecimal(this.Цена) / 100) * this.ДействующаяСкидка;
                }
            }


            //ПРОВЕРКА НА СКИДКУ > 15
            public bool checkActionCollor
            {
                get
                {
                    if (this.ДействующаяСкидка > 15)
                        return true;
                    else
                        return false;
                }
            }

            //ПРОВЕРКА, ЕСТЬ ЛИ ТОВАР НА СКЛАДЕ
            public bool checkCountProduct
            {
                get
                {
                    if (this.КоличествоНаСкладе == 0)
                        return true;
                    else
                        return false;
                }
            }


           
        }
    }
